php_packages:
  - php5-fpm
  - php5-cgi
  - php5-cli
  - php5-curl
  - php5-json
  - php5-odbc
  - php5-tidy
  - php5-common
  - php5-xmlrpc
  - php5-gd
  - php-pear
  - php5-dev
  - php5-imap
  - php5-mcrypt
  - php5-mysqlnd

php_enable_webserver: false
php_webserver_daemon: nginx
php_enable_php_fpm: true
php_memory_limit: "128M"
php_max_execution_time: 90
php_upload_max_filesize: "12M"
