---
## Proftp Configuration.
proftpd_conf_path:  /etc/proftpd/proftpd.conf
proftpd_db: ftpd
proftpd_db_connection: "{{ proftpd_db }}@localhost"
proftpd_db_username: "{{ proftpd_db }}"
proftpd_db_password: "{{ proftpd_db }}"
proftpd_welcome: FTP
proftpd_db_userhost: "%"
proftpd_db_priv: "{{ proftpd_db }}.*:ALL"
