mysql_databases:
  - name: "{{ properties.example.account_username }}"
    encoding: utf8
    collation: utf8_general_ci
  - name: "{{ properties.exemplo.account_username }}"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ properties.example.account_username }}"
    host: "%"
    password: "{{ properties.example.account_password }}"
    priv: "{{ properties.example.account_username }}.*:ALL"
  - name: "{{ properties.exemplo.account_username }}"
    host: "%"
    password: "{{ properties.exemplo.account_password }}"
    priv: "{{ properties.exemplo.account_username }}.*:ALL"
